import type { Metadata } from "next";
import "./globals.css";
import { ReduxProvider } from "@/src/providers/ReduxProvider";
import { useAuthLoad } from "@/hook/useAuthLoad";
import AuthLoaderWrapper from "@/src/providers/AuthLoaderWrapper";

export const metadata: Metadata = {
  title: "Mychat App",
  description: "Generated by chonlapat",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <AuthLoaderWrapper>{children}</AuthLoaderWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
