import type { Metadata } from "next";
import "./globals.css";
import { ReduxProvider } from "@/src/providers/ReduxProvider";

export const metadata: Metadata = {
  title: "Mychat App",
  description: "Generated by chonlapat",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
